[package]
name = "ptp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = { version = "0.5.1", default-features = false }
bitvec = { version = "0.22.3", default-features = false }
fixed = "1.11.0"
arrayvec = { version = "0.7.2", default-features = false }
